<h2><span style="color:red">🚨 Run the below cell to install and import required packages</span></h2>


In [3]:
%pip install numpy_assignment_tests-0.1-py3-none-any.whl --force-reinstall
import numpy as np

Processing ./numpy_assignment_tests-0.1-py3-none-any.whl
  Attempting uninstall: numpy-assignment-tests
    Found existing installation: numpy-assignment-tests 0.1
    Uninstalling numpy-assignment-tests-0.1:
      Successfully uninstalled numpy-assignment-tests-0.1

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


## 📝 **18th April NumPy Class Test - 45 Minute Duration**

---

### ✅ **Problem 1: Array Creation and Basic Operations**

**Steps to solve:**

1. Create a NumPy array of even numbers from 10 to 50 (inclusive).
2. Multiply all elements of the array by 2 and store it in a new variable.
3. Compute the sum of all elements in the doubled array.
4. Reshape the doubled array into a 2D array with 5 rows and 4 columns.

**Function Signature:**

In [4]:
def problem1():
    arr = np.arange(10, 51, 2)  

    arr_doubled = arr * 2

    total = np.sum(arr_doubled)

    reshaped = arr_doubled[:20].reshape(5, 4)

    return arr_doubled, total, reshaped

In [13]:
try:
    from numpy_assignment_tests import test
    test.test_problem1(problem1)
except:
    print("Try Again!")

[✔] Problem 1 Passed — Score: 20/20



---

### ✅ **Problem 2: Indexing and Slicing**

**Steps to solve:**

1. Create a 5x5 NumPy array with numbers from 1 to 25 (row-wise).
2. Extract the 2nd and 4th rows (index 1 and 3).
3. Extract the 3rd column (index 2).
4. Extract a subarray from rows 2 to 4 and columns 2 to 5.

**Function Signature:**

In [14]:
def problem2():
    arr = np.arange(1, 26).reshape(5, 5)
    rows = arr[[1, 3], :]          
    col = arr[:, 2]               
    subarray = arr[2:5, 2:5]     

    return rows, col, subarray

problem2()

(array([[ 6,  7,  8,  9, 10],
        [16, 17, 18, 19, 20]]),
 array([ 3,  8, 13, 18, 23]),
 array([[13, 14, 15],
        [18, 19, 20],
        [23, 24, 25]]))

In [15]:
try:
    from numpy_assignment_tests import test
    test.test_problem2(problem2)
except:
    print("Try Again!")

[✔] Problem 2 Passed — Score: 20/20


---

### ✅ **Problem 3: Boolean Masking and Conditional Operations**

**Steps to solve:**

1. Create a NumPy array of integers from 1 to 20.
2. Use boolean masking to extract all numbers divisible by 3.
3. Replace all numbers greater than 15 in the original array with -1.

**Function Signature:**

In [17]:
def problem3():
    
    arr = np.arange(1, 21)

    divisible_by_3 = arr[arr % 3 == 0]

    replaced_array = np.where(arr > 15, -1, arr)

    return divisible_by_3, replaced_array


In [18]:
try:
    from numpy_assignment_tests import test
    test.test_problem3(problem3)
except:
    print("Try Again!")

[✔] Problem 3 Passed — Score: 20/20


---

### ✅ **Problem 4: Aggregate Functions and Axis Operations**

**Steps to solve:**

1. Create a 4x4 NumPy array with values from 1 to 16.
2. Calculate the mean of each row.
3. Calculate the sum of each column.

**Function Signature:**

In [19]:


def problem4():
    arr = np.arange(1, 17).reshape(4, 4)

    row_means = arr.mean(axis=1)

    col_sums = arr.sum(axis=0)

    return row_means, col_sums



In [20]:
try:
    from numpy_assignment_tests import test
    test.test_problem4(problem4)
except:
    print("Try Again!")

[✔] Problem 4 Passed — Score: 20/20


---

### ✅ **Problem 5: Stacking and Splitting Arrays**

**Steps to solve:**

1. Create two NumPy arrays: `a = [1, 2, 3]`, `b = [4, 5, 6]`.
2. Stack them vertically and horizontally.
3. Split the horizontal stacked array into two equal parts.

**Function Signature:**

In [21]:

def problem5():
    a = np.array([11, 2, 31])
    b = np.array([14, 5, 61])
    
    vstacked = np.vstack((a, b))
    hstacked = np.hstack((a, b))
    
    split_arrays = np.array_split(hstacked, 2)

    return vstacked, hstacked, split_arrays


In [22]:
try:
    from numpy_assignment_tests import test
    test.test_problem5(problem5)
except:
    print("Try Again!")

[✔] Problem 5 Passed — Score: 20/20


<h3><span style="color:red">🚨 Run the below cell to execute all test cases and get the final score</span></h3>


In [24]:
## DO NOT MODIFY ##
try:
    from numpy_assignment_tests import test
    student_name = input("Enter your full name: ").strip()
    test.run_all_tests({
        "problem1": problem1,
        "problem2": problem2,
        "problem3": problem3,
        "problem4": problem4,
        "problem5": problem5
    }, student_name)
except:
    print("Check again and complete all the questions completely!!")

=== NumPy Assignment Evaluation ===
[✔] Problem 1 Passed — Score: 20/20
[✔] Problem 2 Passed — Score: 20/20
[✔] Problem 3 Passed — Score: 20/20
[✔] Problem 4 Passed — Score: 20/20
[✔] Problem 5 Passed — Score: 20/20

🏁 Final Score: 100/100
